version: '2'
services:
    java:
        build: ./
        container_name: java_pubgolf
        ports:
            - '80:80'
        networks:
            - docker_pubgolf

networks:
    docker_pubgolf:
        driver: bridge