services:
  db:
    image: postgres:17
    container_name: pubgolf-db
    environment:
      POSTGRES_USER: pubgolf
      POSTGRES_PASSWORD: pubgolf
      POSTGRES_DB: pubgolf
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./apps/backend
    container_name: pubgolf-backend
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ./apps/frontend
    container_name: pubgolf-frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080
    ports:
      - "3000:3000"
    depends_on:
      - backend