security:
  oauth2:
    client:
      clientId: XXX
      clientSecret: XXX
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me

server:
  port: 80

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp