spring:
  application:
    name: pubgolf
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: pubgolf
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    enabled: true
    locations: classpath:db/migration

application:
  origins: http://192.168.0.135:3000, http://localhost:3000
  server: http://localhost:8080
