CREATE TABLE game (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    identifier VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE player (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    scores VARCHAR(255) NOT NULL DEFAULT '0,0,0,0,0,0,0,0,0',
    game_id BIGINT,
    FOREIGN KEY (game_id) REFERENCES game (id)
);
